import type {Metadata} from 'next';
import './globals.css';
import { RootProvider } from 'fumadocs-ui/provider/next';
import { SITE_URL } from '@/lib/site';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: 'Backstop — In-Process Reliability Layer for AI SDKs',
  description:
    'Backstop is an in-process reliability layer for AI SDKs providing backpressure, budget enforcement, circuit breaking, and telemetry for multi-agent workflows.',
  // The card is generated by scripts/make_og.py, which draws it from this
  // site's own palette and reads the version back off PyPI so it cannot
  // advertise one that was never published. It was declared as
  // summary_large_image with no image behind it, so every share of the link
  // rendered blank.
  openGraph: {
    title: 'Backstop — In-Process Reliability Layer for AI SDKs',
    description:
      'Backstop is an in-process reliability layer for AI SDKs providing backpressure, budget enforcement, circuit breaking, and telemetry for multi-agent workflows.',
    type: 'website',
    url: '/',
    images: [
      {
        url: '/og.png',
        width: 1200,
        height: 630,
        alt: 'Backstop — in-process reliability for AI SDKs',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Backstop — In-Process Reliability Layer for AI SDKs',
    description:
      'Backstop is an in-process reliability layer for AI SDKs providing backpressure, budget enforcement, circuit breaking, and telemetry for multi-agent workflows.',
    images: ['/og.png'],
  },
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className="bg-background text-foreground antialiased selection:bg-secondary selection:text-secondary-foreground font-sans">
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
